userlist:
  title: User list
  desctiption: Lists users
  icon: icon-group
  settings:
    fields:
      displayMode:
        type: select
        title: 'What to display'
        options:
          - 'members:Members'
          - 'following:Following'
          - 'followers:Followers'
        default: 'members'
      pageSize:
        type: select
        title: 'Users per page'
        default: 10
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 30
          - 50
          - 100
      paging:
        type: select
        title: 'Paging controls'
        default: 'show'
        options:
          - 'show:Show'
          - 'hide:Hide'

account:
  title: User account
  desctiption: Allows users to edit account details
  icon: icon-cog
  special: account

profile:
  title: User profile
  desctiption: User profile information
  icon: icon-user
  special: profile

login:
  title: Sign up form
  desctiption: Sign up form for this group
  icon: icon-lock
  special: register

resetpassword:
  title: Reset password
  desctiption: Reset password widget
  icon: icon-lock
  special: resetpassword